steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-key'
    entrypoint: 'bash'
    dir:
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret="github" --project="vertex-325021" > /root/.ssh/id_rsa
    volumes:
      - name: 'ssh'
        path: /root/.ssh

    
options:
  subscription_options: 'ALLOW_LOOSE'


substitutions:
  _BASE_BRANCH: "main"


timeout: 10000s
